# Generated by Django 3.0.3 on 2020-02-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
